Repository Rabbittee/body-composition, pull requests merged in 2022-08, with the labels that each got.

#31 feat: Mobile view
  src/components/home/Header/Header.tsx
  src/components/home/InputForm/InputForm.tsx
  src/components/home/Result/Options.ts
  src/components/home/Result/Result.tsx
  src/components/home/Result/ResultEntity.tsx
  src/components/home/Result/ResultList.tsx
  src/components/home/Result/ResultValue.tsx
  src/components/layouts/Main.tsx
  src/pages/Home/Home.tsx
Labels: WIP, enhancement

#40 test: 💍 utils/TDEE
  src/utils/TDEE/__test__/FAO.test.ts
  src/utils/TDEE/__test__/redman.test.ts
  src/utils/TDEE/__test__/testCase.ts
Labels: enhancement

#25 feat: add testCase for utils/BMR
  src/utils/BMR/__test__/katchMcArdle.test.ts
  src/utils/BMR/__test__/mifflinStJeor.test.ts
  src/utils/BMR/__test__/oxfordEquation.test.ts
  src/utils/BMR/__test__/revisedHarrisBenedict.test.ts
  src/utils/BMR/__test__/robertsonAndReid.test.ts
  src/utils/BMR/__test__/testCase.ts
Labels: enhancement

#58 hotfix: bodyinfo model update
  src/components/home/InputForm/InputForm.tsx
Labels: bug
